state_bird_list = [
    "Yellowhammer",
    "Willow Ptarmigan",
    "Cactus Wren",
    "Northern Mockingbird",
    "California Valley Quail",
    "Lark Bunting",
    "American Robin",
    "Blue Hen Chicken",
    "Mockingbird",
    "Brown Thrasher",
    "Nene",
    "Mountain Bluebird",
    "Cardinal",
    "Cardinal",
    "Eastern Goldfinch",
    "Western Meadowlark",
    "Cardinal",
    "Eastern Brown Pelican",
    "Chickadee",
    "Baltimore Oriole",
    "Chickadee",
    "Robin",
    "Common Loon",
    "Mockingbird",
    "Bluebird",
    "Western Meadowlark",
    "Western Meadowlark",
    "Mountain Bluebird",
    "Purple Finch",
    "Eastern Goldfinch",
    "Roadrunner",
    "Eastern Bluebird",
    "Cardinal",
    "Western Meadowlark",
    "Cardinal",
    "Scissor-tailed Flycatcher",
    "Western Meadowlark",
    "Ruffed Grouse",
    "Rhode Island Red Hen",
    "Carolina Wren",
    "Ring-necked Pheasant",
    "Mockingbird",
    "Mockingbird",
    "Ring-billed Gull",
    "Hermit Thrush",
    "Cardinal",
    "Willow Goldfinch",
    "Cardinal",
    "Robin",
    "Western Meadowlark",
]

state_capitals = [
    "Montgomery",
    "Juneau",
    "Phoenix",
    "Little Rock",
    "Sacramento",
    "Denver",
    "Hartford",
    "Dover",
    "Tallahassee",
    "Atlanta",
    "Honolulu",
    "Boise",
    "Springfield",
    "Indianapolis",
    "Des Moines",
    "Topeka",
    "Frankfort",
    "Baton Rouge",
    "Augusta",
    "Annapolis",
    "Boston",
    "Lansing",
    "Saint Paul",
    "Jackson",
    "Jefferson City",
    "Helena",
    "Lincoln",
    "Carson City",
    "Concord",
    "Trenton",
    "Santa Fe",
    "Albany",
    "Raleigh",
    "Bismarck",
    "Columbus",
    "Oklahoma City",
    "Salem",
    "Harrisburg",
    "Providence",
    "Columbia",
    "Pierre",
    "Nashville",
    "Austin",
    "Salt Lake City",
    "Montpelier",
    "Richmond",
    "Olympia",
    "Charleston",
    "Madison",
    "Cheyenne",
]
