full_state_dictionary = {
    "AL": {
        "bird": "Yellowhammer",
        "capital": "Montgomery",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Alabama",
        "population": "holder",
    },
    "AK": {
        "bird": "Willow Ptarmigan",
        "capital": "Juneau",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Alaska",
        "population": "holder",
    },
    "AZ": {
        "bird": "Cactus Wren",
        "capital": "Phoenix",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Arizona",
        "population": "holder",
    },
    "AR": {
        "bird": "Northern Mockingbird",
        "capital": "Little Rock",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Arkansas",
        "population": "holder",
    },
    "CA": {
        "bird": "California Valley Quail",
        "capital": "Sacramento",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "California",
        "population": "holder",
    },
    "CO": {
        "bird": "Lark Bunting",
        "capital": "Denver",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Colorado",
        "population": "holder",
    },
    "CT": {
        "bird": "American Robin",
        "capital": "Hartford",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Connecticut",
        "population": "holder",
    },
    "DE": {
        "bird": "Blue Hen Chicken",
        "capital": "Dover",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Delaware",
        "population": "holder",
    },
    "FL": {
        "bird": "Mockingbird",
        "capital": "Tallahassee",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Florida",
        "population": "holder",
    },
    "GA": {
        "bird": "Brown Thrasher",
        "capital": "Atlanta",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Georgia",
        "population": "holder",
    },
    "HI": {
        "bird": "Nene",
        "capital": "Honolulu",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Hawaii",
        "population": "holder",
    },
    "ID": {
        "bird": "Mountain Bluebird",
        "capital": "Boise",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Idaho",
        "population": "holder",
    },
    "IL": {
        "bird": "Cardinal",
        "capital": "Springfield",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Illinois",
        "population": "holder",
    },
    "IN": {
        "bird": "Cardinal",
        "capital": "Indianapolis",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Indiana",
        "population": "holder",
    },
    "IA": {
        "bird": "Eastern Goldfinch",
        "capital": "Des Moines",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Iowa",
        "population": "holder",
    },
    "KS": {
        "bird": "Western Meadowlark",
        "capital": "Topeka",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Kansas",
        "population": "holder",
    },
    "KY": {
        "bird": "Cardinal",
        "capital": "Frankfort",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Kentucky",
        "population": "holder",
    },
    "LA": {
        "bird": "Eastern Brown Pelican",
        "capital": "Baton Rouge",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Louisiana",
        "population": "holder",
    },
    "ME": {
        "bird": "Chickadee",
        "capital": "Augusta",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Maine",
        "population": "holder",
    },
    "MD": {
        "bird": "Baltimore Oriole",
        "capital": "Annapolis",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Maryland",
        "population": "holder",
    },
    "MA": {
        "bird": "Chickadee",
        "capital": "Boston",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Massachusetts",
        "population": "holder",
    },
    "MI": {
        "bird": "Robin",
        "capital": "Lansing",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Michigan",
        "population": "holder",
    },
    "MN": {
        "bird": "Common Loon",
        "capital": "Saint Paul",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Minnesota",
        "population": "holder",
    },
    "MS": {
        "bird": "Mockingbird",
        "capital": "Jackson",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Mississippi",
        "population": "holder",
    },
    "MO": {
        "bird": "Bluebird",
        "capital": "Jefferson City",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Missouri",
        "population": "holder",
    },
    "MT": {
        "bird": "Western Meadowlark",
        "capital": "Helena",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Montana",
        "population": "holder",
    },
    "NE": {
        "bird": "Western Meadowlark",
        "capital": "Lincoln",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Nebraska",
        "population": "holder",
    },
    "NV": {
        "bird": "Mountain Bluebird",
        "capital": "Carson City",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Nevada",
        "population": "holder",
    },
    "NH": {
        "bird": "Purple Finch",
        "capital": "Concord",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "New Hampshire",
        "population": "holder",
    },
    "NJ": {
        "bird": "Eastern Goldfinch",
        "capital": "Trenton",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "New Jersey",
        "population": "holder",
    },
    "NM": {
        "bird": "Roadrunner",
        "capital": "Santa Fe",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "New Mexico",
        "population": "holder",
    },
    "NY": {
        "bird": "Eastern Bluebird",
        "capital": "Albany",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "New York",
        "population": "holder",
    },
    "NC": {
        "bird": "Cardinal",
        "capital": "Raleigh",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "North Carolina",
        "population": "holder",
    },
    "ND": {
        "bird": "Western Meadowlark",
        "capital": "Bismarck",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "North Dakota",
        "population": "holder",
    },
    "OH": {
        "bird": "Cardinal",
        "capital": "Columbus",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Ohio",
        "population": "holder",
    },
    "OK": {
        "bird": "Scissor-tailed Flycatcher",
        "capital": "Oklahoma City",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Oklahoma",
        "population": "holder",
    },
    "OR": {
        "bird": "Western Meadowlark",
        "capital": "Salem",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Oregon",
        "population": "holder",
    },
    "PA": {
        "bird": "Ruffed Grouse",
        "capital": "Harrisburg",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Pennsylvania",
        "population": "holder",
    },
    "RI": {
        "bird": "Rhode Island Red Hen",
        "capital": "Providence",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Rhode Island",
        "population": "holder",
    },
    "SC": {
        "bird": "Carolina Wren",
        "capital": "Columbia",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "South Carolina",
        "population": "holder",
    },
    "SD": {
        "bird": "Ring-necked Pheasant",
        "capital": "Pierre",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "South Dakota",
        "population": "holder",
    },
    "TN": {
        "bird": "Mockingbird",
        "capital": "Nashville",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Tennessee",
        "population": "holder",
    },
    "TX": {
        "bird": "Mockingbird",
        "capital": "Austin",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Texas",
        "population": "holder",
    },
    "UT": {
        "bird": "Ring-billed Gull",
        "capital": "Salt Lake City",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Utah",
        "population": "holder",
    },
    "VT": {
        "bird": "Hermit Thrush",
        "capital": "Montpelier",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Vermont",
        "population": "holder",
    },
    "VA": {
        "bird": "Cardinal",
        "capital": "Richmond",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Virginia",
        "population": "holder",
    },
    "WA": {
        "bird": "Willow Goldfinch",
        "capital": "Olympia",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Washington",
        "population": "holder",
    },
    "WV": {
        "bird": "Cardinal",
        "capital": "Charleston",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "West Virginia",
        "population": "holder",
    },
    "WI": {
        "bird": "Robin",
        "capital": "Madison",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Wisconsin",
        "population": "holder",
    },
    "WY": {
        "bird": "Western Meadowlark",
        "capital": "Cheyenne",
        "flower": "holder",
        "governor": "holder",
        "land_area": "holder",
        "name": "Wyoming",
        "population": "holder",
    },
}
