gov_dictionary = {
    "AL": {
        "gov_name": "Kay Ivey",
        "terms": "2017",
        "birthdate": "October 15, 1944",
        "bith_state": "Alabama",
        "school": "University of Auburn",
        "bio": [
            "Growing up in the small town of Camden in Wilcox County, Alabama, and working on her father’s farm taught Kay Ivey to value hard work and living within one’s means. Her parents instilled values of faith, family and community.",
            "After graduating from Auburn University in 1967, Kay worked as a high school teacher and a bank officer. She served as Reading Clerk of the Alabama House of Representatives under Speaker Joseph C. McCorquodale and was Assistant Director of the Alabama Development Office, where she worked to spur job creation and economic development across the state.",
            "On April 10, 2017, Kay was sworn in as the 54th Governor of the state of Alabama in the Old Senate Chamber in the Alabama State Capitol by Acting Chief Justice Lyn Stuart. Following a successful nineteen months in office, the people of Alabama made history again in November 2018 by electing Governor Ivey to a full term. She is the first Lt. Governor of Alabama elected to a full term after taking over as governor due to a vacancy in the Governor’s Office. Governor Ivey was reelected to a second full term November 2022 and she was sworn in January 16, 2023. Noting education, economic development, roads and bridges, broadband expansion, public safety and government reform as the top priorities of her second administration.",
        ],
    },
    "AK": {
        "gov_name": "Mike Dunleavy",
        "terms": "2018",
        "birthdate": "May 5, 1961",
        "bith_state": "Pennsylvania",
        "school": "Misericordia University; University of Alaska Fairbanks",
        "bio": [
            "Governor Mike Dunleavy arrived in Alaska in 1983 as a young man looking for opportunity, and he found it. His first job was working in a logging camp in Southeast Alaska. Later on, Governor Dunleavy pursued his dream of becoming a teacher. He earned his teacher’s certificate, and then a master of education degree from the University of Alaska Fairbanks. He spent nearly two decades in northwest Arctic communities working as a teacher, principal, and superintendent.",
            "Governor Dunleavy’s wife Rose is from the Kobuk River Valley community of Noorvik. Together, they have three children – Maggie, Catherine, and Ceil – who were raised in both rural and urban Alaska.",
            "Governor Dunleavy and his family moved to Wasilla in 2004, where he owned an educational consulting firm and worked on a number of educational projects statewide. Dunleavy served on the Mat-Su Borough School Board, with two years as Board President, and then as a state senator for five years.",
        ],
    },
    "AZ": {
        "gov_name": "Katie Hobbs",
        "terms": "2023",
        "birthdate": "December 28, 1969",
        "bith_state": "Arizona",
        "school": "Northern Arizona University,  Arizona State University",
        "bio": [
            "Born and raised in Arizona, Governor Hobbs has spent her life exemplifying hard work and public service. After putting herself through college at both NAU and ASU, she began her career as a social worker working with homeless youth and later helped run one of the largest domestic violence shelters in the country. After seeing her fellow Arizonans continue to struggle with little action from the government, Governor Hobbs decided to take matters into her own hands and run for office.",
            "After being elected to the Arizona House in 2010, Governor Hobbs went on to serve in the Arizona State Legislature for four terms, including two as Senate Minority Leader. After working across the aisle to deliver for Arizonans, Governor Hobbs saw an opportunity to use her leadership skills to serve Arizonans across the state. In 2018, she was elected Secretary of State, where she successfully oversaw a contentious election cycle and forcefully defended the votes and voices of every single Arizonan. Seeing her home state at a critical turning point, Governor Hobbs made the decision to run for Governor, and in 2022 was elected the fifth woman, and also fifth Arizona native, to lead the state.",
            "With over a decade of public service, Governor Hobbs sees her role in government as a continuation of her social work. In her first term, she has already moved the needle forward on some of our state’s most critical issues, including housing, water security, and economic development. Governor Hobbs approaches every situation and every challenge with a desire to make people’s lives better and give every Arizonan an opportunity to thrive.",
        ],
    },
    "AR": {
        "gov_name": "Sarah Huckabee Sanders",
        "terms": "2023",
        "birthdate": "August 13, 1982",
        "bith_state": "Arkansas",
        "school": "Ouachita Baptist University",
        "bio": [
            "Sarah Huckabee Sanders is the 47th Governor of Arkansas.",
            "Inaugurated on January 10, 2023, she is the first woman to serve as governor of the state and currently is the youngest governor in the country.",
            "Prior to her historic victory, Sarah served as White House Press Secretary for President Donald J. Trump from 2017 to 2019. A trusted confidant of the President, she advised him on everything from press and communications strategy to personnel and policy. For two and a half years, Sarah worked closely with the president, battling with the media, working with lawmakers and CEOs, and accompanying the president on every foreign trip, including dozens of meetings with foreign leaders. Sarah was only the third woman – and the very first mom – to ever hold the job of White House Press Secretary.",
        ],
    },
    "CA": {
        "gov_name": "Gavin Newsom",
        "terms": "2019",
        "birthdate": "October 10, 1967",
        "bith_state": "California",
        "school": "Santa Clara University",
        "bio": [
            "Gavin Newsom is the Governor of California, former Lieutenant Governor of California, and former Mayor of San Francisco. Governor Newsom’s top priorities for his administration are tackling our state’s affordability crisis, creating inclusive economic growth and opportunity for every child, and standing up for California values — from civil rights, to immigration, environmental protection, access to quality schools at all levels, and justice.",
            "Governor Newsom is married to Jennifer Siebel Newsom. They have four children: Montana, Hunter, Brooklynn, and Dutch.",
        ],
    },
    "CO": {
        "gov_name": "Jared Polis",
        "terms": "2019",
        "birthdate": "May 12, 1975",
        "bith_state": "Colorado",
        "school": "Princeton University",
        "bio": [
            "Governor Jared Polis is an entrepreneur, education leader, public servant, and Colorado native. After launching several successful companies, including one out of his college dorm room, Polis committed himself to making sure other Coloradans had the opportunity to pursue their dreams. Polis founded schools for at-risk students and new immigrants and started nonprofits to help veterans and entrepreneurs.",
            "Prior to serving as Governor, Polis served on the State Board of Education where he worked to raise pay for teachers and reduce class size for students, and represented Colorado’s 2nd Congressional district, where he was rated the most effective member of the Colorado delegation.",
            "As Governor, Polis has focused on saving Coloradans money, keeping our economy strong, and preserving our Colorado way of life. Polis delivered universal free full-day kindergarten, signed a number of bills to save families money on health care, and made significant progress towards the goal of 100% renewable energy by 2040, all while cutting taxes for small businesses and investing in affordable housing and transportation. His efforts to expand health care access to medically underserved communities and to ensure that equity and justice remain central to building a Colorado for All have produced impactful legislation and made progress toward his administration’s bold vision.",
        ],
    },
    "CT": {
        "gov_name": "Ned Lamont",
        "terms": "2019",
        "birthdate": "January 3, 1954",
        "bith_state": "Washington, D.C.",
        "school": "Harvard University; Yale University",
        "bio": [
            "Ned Lamont was sworn into office as the 89th governor of Connecticut on January 9, 2019. He began his second term on January 4, 2023.",
            "Lamont got involved in public service shortly after college, founding a weekly newspaper in a town hit by the loss of its largest employer. Covering town meetings and the Board of Selectmen, he helped to bring voice and transparency to a community working to recover from job losses and reinvent itself. Later, as a member of both the Greenwich Board of Selectmen and the Board of Estimate and Taxation, Lamont worked in a bipartisan effort to safeguard a multimillion-dollar budget and deliver results for constituents. For four years, Lamont also served as Chairman of the State Investment Advisory Council, overseeing a multibillion-dollar state pension fund.",
            "Lamont started his own company, taking on the large and established giants of the telecom industry. Under his vision and stewardship, the company grew to serve over 400 of America’s largest college campuses and 1 million college students across the nation.",
        ],
    },
    "DE": {
        "gov_name": "John Carney",
        "terms": "2017",
        "birthdate": "May 20, 1956",
        "bith_state": "Delaware",
        "school": "Dartmouth College; University of Delaware",
        "bio": [
            "Born in Wilmington and raised in Claymont, Governor John Carney has been working for the Delaware people for more than 30 years. Governor Carney took office as Delaware’s 74th Governor in January 2017, focused on making Delaware’s economy more competitive, preparing Delaware’s children to succeed, and building a long-term sustainable financial plan for the State of Delaware. Working with Delawareans across the state, and with members of the General Assembly, he has made progress on each of those priorities. Governor Carney has directed new resources to high-needs schools, partnered with the private sector to drive new job creation, and taken steps to lower healthcare costs for Delaware families, businesses, and taxpayers.",
            "Governor Carney began his second term Governor on January 19, 2021. Throughout the COVID-19 crisis, Governor Carney has attempted to balance the need for a healthy community with the need for a strong economy. Working with Delawareans, our communities, and Members of the General Assembly, Governor Carney remains focused on beating COVID-19, rebuilding our economy, making sure all Delaware children have an opportunity to succeed, and recommitting to a long-term sustainable financial plan for the State of Delaware.",
        ],
    },
    "FL": {
        "gov_name": "Ron DeSantis",
        "terms": "2019",
        "birthdate": "September 14, 1978",
        "bith_state": "Florida",
        "school": "Yale University, Harvard Law School",
        "bio": [
            "Governor Ron DeSantis is the former U.S. Representative for Florida’s Sixth District. A native Floridian with blue-collar roots, Ron worked his way through Yale University, where he graduated with honors and was the captain of the varsity baseball team. He also graduated with honors from Harvard Law School. While at Harvard, he earned a commission in the U.S. Navy as a JAG officer. After active-duty service, Ron served as a federal prosecutor. He was first elected to Congress in 2012."
        ],
    },
    "GA": {
        "gov_name": "Brian Kemp",
        "terms": "2019",
        "birthdate": "November 2, 1963",
        "bith_state": "Georgia",
        "school": "University of Georgia",
        "bio": [
            "A native of Athens, Georgia, Brian Kemp started his first small business over 35 years ago with a pickup truck and a shovel. His experience as a small business owner has driven his mission to put hardworking Georgians first since taking office as Georgia’s 83rd governor in 2019.",
            "Throughout his first term, the Peach State consistently broke economic records, with jobs and investments coming to every region of the state.\xa0In 2022, Governor Kemp was re-elected to serve a second term, running on a record of economic success in the Peach State and a plan to help Georgia families fight through 40-year-high inflation while strengthening public safety and improving education. He has championed legislation to crack down on violent crimes and street gangs, end human trafficking and support its victims, enact historic tax cuts for families, give teachers historic pay raises, and ensure Georgia’s K-12 education system puts students and parents first.",
            "Governor Kemp, First Lady Marty Kemp, and their three adult daughters live on their family farm in Athens.",
        ],
    },
    "HI": {
        "gov_name": "Josh Green",
        "terms": "2022",
        "birthdate": "February 11, 1970",
        "bith_state": "Pennsylvania",
        "school": "Swarthmore College, Pennsylvania State University and the University of Pittsburgh",
        "bio": [
            "Governor Josh Green is a proud husband, father, physician, and Hawaiʻiʻs ninth governor. Raised in Pittsburgh, Pennsylvania, Governor Green received his degree in both biology and anthropology from Swarthmore College and his M.D. from Penn State Milton S. Hershey Medical Center at Pennsylvania State University. After graduating medical school he completed his residency in Family Practice. He was then awarded a National Health Service Corps scholarship and chose a position to practice medicine in the underserved area of Kā’ū on the Big Island of Hawai’i.\xa0",
            "After learning about their struggles and hearing directly from the people about the need for change, he ran for office. He served in the Hawaiʻi State House of Representatives from 2004 to 2008. From 2008 to 2018, he served in the Hawaiʻi State Senate, including as Majority Floor Leader, Chair of the Health and Human Services committees, and Vice Chair of the Energy and Environment, and Human Services and Housing committees. Governor Green was recognized for his leadership in healthcare, providing health insurance for every child in the state of Hawaii, and passing “Lukeʻs Law,” which provides insurance coverage for kids with autism. He also helped spearhead the creation of the Cancer Research Center, passed groundbreaking anti-tobacco legislation, which increased the legal age for purchasing tobacco and e-cigarettes to 21, and created a statewide trauma healthcare system.\xa0\xa0",
            "In 2018, he was elected to be the Lieutenant Governor of Hawaiʻi. As Lieutenant Governor, he saw the need for real solutions on homelessness and helped build “kauhale” communities and the H4 clinic to provide housing and healthcare for those most in need. In 2019 when the measles epidemic hit, he led a team of more than 75 doctors, nurses, and other medical professionals on an emergency mission to Western Samoa. His team successfully vaccinated 37,000 people.\xa0",
        ],
    },
    "ID": {
        "gov_name": "Brad Little",
        "terms": "2019",
        "birthdate": "February 15, 1954",
        "bith_state": "Idaho",
        "school": "University of Idaho",
        "bio": [
            "The people of Idaho elected Brad Little as the state’s 33rd Governor in November 2018. He became Governor on January 7, 2019. Governor Littleis an Emmett native who was raised on his family’s sheep and cattle ranching operation. He graduated from the University of Idaho in 1977 with a Bachelor of Science in Agribusiness, and has worked in the ranching industry for his entire professional life. Governor Little first served in public office in 2001 when he was selected to fill a Senate vacancy. He was then elected to four consecutive terms to the Idaho Senate. During his service as a Senator, Governor Little was elected by his Republican peers during his first full term to serve in Party leadership as Majority Caucus Chair. He then served as Idaho’s 37th Lt. Governor starting on January 6, 2009."
        ],
    },
    "IL": {
        "gov_name": "J. B. Pritzker",
        "terms": "2019",
        "birthdate": "January 19, 1965",
        "bith_state": "California",
        "school": "Duke University; Northwestern University School of Law",
        "bio": [
            "Governor JB Pritzker was sworn in as the 43rd Governor of Illinois on Jan. 14, 2019. Since taking office, he has accomplished one of the most ambitious and consequential policy agendas in state history.",
            "The governor won bipartisan passage for Rebuild Illinois, the largest investment in state history to upgrade roads, bridges, rail, broadband, and schools. He overcame years of fiscal mismanagement in Illinois by proposing and passing a balanced budget every year, eliminating the state’s multi-billion dollar bill backlog, reducing the state’s pension liability, and achieving six credit upgrades from rating agencies. He took bold action to put state government back on the side of working families by creating jobs, raising the minimum wage to a living wage, protecting reproductive rights, making university and community college education more affordable, and advancing equal pay for women.",
        ],
    },
    "IN": {
        "gov_name": "Eric Holcomb",
        "terms": "2017",
        "birthdate": "May 2, 1968",
        "bith_state": "Indiana",
        "school": "Hanover College",
        "bio": [
            "Governor Eric J. Holcomb is the 51st Governor of Indiana. A lifelong Hoosier, Gov. Holcomb is a veteran of the United States Navy, served as the state’s 51st Lt. Governor, was a trusted advisor to both Gov. Mitch Daniels and Sen. Dan Coats, worked for Congressman John Hostettler and is a former state chairman of the Indiana Republican Party. He was elected governor in November 2016. The governor is a graduate of Pike High School in Indianapolis and Hanover College in southeastern Indiana where he majored in U.S. History with a focus on the American Civil War and the Reconstruction Era. He is a collector of presidential signatures and currently has documents signed by all 44 of our nation’s presidents."
        ],
    },
    "IA": {
        "gov_name": "Kim Reynolds",
        "terms": "2017",
        "birthdate": "August 4, 1959",
        "bith_state": "Iowa",
        "school": "Iowa State University",
        "bio": [
            "Governor Kim Reynolds is the 43rd governor of Iowa and has the distinction of being the first woman elected to the state’s highest office.",
            "Governor Reynolds has a long-standing record of public service, having served four terms as Clarke County Treasurer before being elected to the Iowa Senate in November 2008. Two years later, as running mate of former Governor Terry Branstad, she was elected Lieutenant Governor and served nearly two terms before succeeding Branstad as Governor of Iowa in May 2017. She was elected in November 2018 to her first full term in office and re-elected in November 2022 to a second term.",
            "Governor Reynolds is proud of her Iowa roots. A small-town, rural Iowan at heart, she grew up in Madison County, graduated from Interstate 35 Community Schools in 1977, married her husband Kevin Reynolds in 1982, worked and raised three daughters, and completed her bachelor’s degree from Iowa State University in 2016 while serving as Lieutenant Governor.",
        ],
    },
    "KS": {
        "gov_name": "Laura Kelly",
        "terms": "2019",
        "birthdate": "January 24, 1950",
        "bith_state": "New York",
        "school": "Bradley University; Indiana University",
        "bio": [
            "Governor Laura Kelly grew up in a career military family where she learned the importance of service, integrity, and accountability. She has made it her life’s work to fight for children and families as a four-term state senator and now in her second term as the 48th Governor of the State of Kansas.",
            "In her first term, Governor Kelly worked with both parties to balance the budget, fully fund schools, repair the state’s infrastructure, reform the child welfare system, and break records for business investment and job creation. She ended her first term with the largest budget surplus in history – even while cutting taxes for working families.",
            "After putting Kansas back on track, Governor Kelly was re-elected to a second term, which began on January 9, 2023.",
        ],
    },
    "KY": {
        "gov_name": "Andy Beshear",
        "terms": "2019",
        "birthdate": "November 29, 1977",
        "bith_state": "Kentucky",
        "school": "Vanderbilt University; University of Virginia School of Law",
        "bio": [
            "Governor Andy Beshear grew up in Fayette, Franklin, and Clark counties and graduated from Henry Clay High School. He is the son of Steve and Jane Beshear, the 61st Governor and first lady. Gov. Beshear graduated magna cum laude from Vanderbilt University and earned his Juris Doctor degree from the University of Virginia School of Law, where he was a Dean’s Scholar. After law school, he worked at an international law firm based in Washington, D.C., and it was during that time that he met his wife, Britainy. Andy and Britainy have two young children, Will and Lila. The family attends Beargrass Christian Church, where both Andy and Britainy serve as deacons, and they volunteer with several local organizations."
        ],
    },
    "LA": {
        "gov_name": "John Bel Edwards",
        "terms": "2016",
        "birthdate": "September 16, 1966",
        "bith_state": "Louisiana",
        "school": "U.S. Military Academy at West Point; Louisiana State University Law Center",
        "bio": [
            "Governor John Bel Edwards was born seventh out of eight children to Sheriff Frank Jr. and Dora Jean Edwards. He grew up hunting and fishing in Amite, a rural town in Tangipahoa Parish. He and First Lady Donna Edwards began dating while students at Amite High School. After graduating top of his class, Gov. Edwards attended the United States Military Academy at West Point. As a cadet, he completed Airborne School and served as vice-chairman of the panel that enforces the West Point Honor Code. The governor graduated from West Point in 1988, commissioning as a second lieutenant in the U.S. Army. He served on active duty for 8 years, earning Airborne, Ranger and Jumpmaster status, culminating with command of a rifle company in the 82nd Airborne Division at Fort Bragg, North Carolina.",
            "In 2008, the people of House District 72 elected him to the Louisiana House of Representatives, where he represented the people of Amite, Greensburg, Kentwood and Hammond for eight years before being elected governor in November 2015. On January 11, 2016, John Bel Edwards was sworn in as the 56th Governor of Louisiana. On November 16, 2019, the people of Louisiana re-elected Gov. Edwards to another four-year term. On January 13, 2020, Gov. Edwards was sworn into his second term as the 56th Governor of Louisiana.",
        ],
    },
    "ME": {
        "gov_name": "Janet Mills",
        "terms": "2019",
        "birthdate": "December 30, 1947",
        "bith_state": "Maine",
        "school": "University of Massachusetts at Boston, University of Maine School of Law",
        "bio": [
            "Janet Trafton Mills was sworn in as the 75th Governor of Maine on Wednesday, January 2, 2019.",
            "Governor Mills is the first woman governor of Maine. In her historic victory, she earned more votes than any governor in state history and is the first governor since 1966 to win a majority of the vote for her first term.",
            "As Governor, she has led Maine through a global pandemic with nation-leading results, including one of the highest vaccination rates and one of the lowest death rates in the country, protecting the lives and livelihoods of Maine people.",
        ],
    },
    "MD": {
        "gov_name": "Wes Moore",
        "terms": "2023",
        "birthdate": "October 15, 1978",
        "bith_state": "Maryland",
        "school": "Valley Forge Military College, Johns Hopkins University",
        "bio": [
            "Wes Moore is the 63rd Governor of the state of Maryland. He is Maryland’s first Black Governor in the state’s 246-year history, and is just the third African American elected Governor in the history of the United States.",
            "Moore is a proud graduate of Valley Forge Military Academy and College, where he received an Associate’s degree in 1998, and was commissioned as a second lieutenant in the U.S. Army. Afterward, he went on to earn his Bachelor’s in international relations and economics at Johns Hopkins University in Baltimore, where he graduated Phi Beta Kappa. While at Johns Hopkins, Moore interned in the office of former Baltimore Mayor Kurt Schmoke. Moore was the first Black Rhodes Scholar in the history of Johns Hopkins University. As A Rhodes Scholar, he earned a Master’s in international relations from Wolfson College at Oxford. In 2005, Moore deployed to Afghanistan as a captain with the 82nd Airborne Division, leading soldiers in combat. Immediately upon returning home, Moore served as a White House Fellow, advising on issues of national security and international relations.",
        ],
    },
    "MA": {
        "gov_name": "Maura Healey",
        "terms": "2023",
        "birthdate": "February 8, 1971",
        "bith_state": "Maryland",
        "school": "Harvard University, Northeastern University",
        "bio": [
            "Maura Healey is the 73rd Governor of Massachusetts. She was sworn in on January 5, 2023, becoming the first woman and first openly LGBTQ person elected Governor in Massachusetts history.",
            "Governor Healey and Lieutenant Governor Driscoll are building an experienced, diverse team that is focused on bringing people together and delivering results for Massachusetts residents. They’re committed to making Massachusetts more affordable and growing the state’s economic competitiveness by prioritizing housing, transportation, job training and child care. They believe that Massachusetts has the greatest collection of human and intellectual capital, business, innovation, and know-how in the world. They are harnessing these resources to deliver for residents, families, and businesses throughout the entire state.",
        ],
    },
    "MI": {
        "gov_name": "Gretchen Whitmer",
        "terms": "2019",
        "birthdate": "August 23, 1971",
        "bith_state": "Michigan",
        "school": "Michigan State University, Michigan State University College of Law",
        "bio": [
            "Governor Gretchen Whitmer is a lifelong Michigander who is focused on getting things done that will make a real difference in people’s lives. As governor, she has signed over 1,000 bipartisan bills and four balanced, bipartisan budgets to deliver on the kitchen-table issues, grow the economy, and create good-paying jobs in every region of the state.",
            "Since the governor took office, Michigan has announced 25,000 auto jobs, will fix 16,000 lane miles of road and 1,200 bridges by the end of 2022, and funded programs putting tens of thousands of people on tuition-free paths to higher education and skills training. She has worked across the aisle to empower Michigan’s economic development and brought critical supply chains home from China to Michigan.",
            "The governor has made the largest education investments in state history four years in a row, delivering the highest state per-student funding ever, increasing on-campus mental health resources, and helping hire thousands more qualified teachers. Additionally, the governor has expanded low or no-cost child care to 150,000 kids and enrolled 35,000 four-year-olds in affordable, high-quality pre-K.",
        ],
    },
    "MN": {
        "gov_name": "Tim Walz",
        "terms": "2019",
        "birthdate": "April 6, 1964",
        "bith_state": "Nebraska",
        "school": "Unlisted",
        "bio": [
            "Tim Walz is Minnesota’s 41st Governor. His career has been defined by public service, from serving our country in the military to serving our students as a high-school teacher and football coach to serving our state in Congress.",
            "Born in a small town in rural Nebraska, Tim’s parents instilled in him the values that guide his commitment to common good and selfless service. Soon after his high school graduation, Tim enlisted in the Army National Guard. Tim attended Chadron State College, where he graduated with a social science degree in 1989. Harvard University offered Tim an opportunity to gain a new perspective on global education by teaching in the People’s Republic of China from 1989-90, where he joined of one of the first government-approved groups of American teachers to work in Chinese high schools. Upon his return from China to Nebraska, Tim served full time in the Army National Guard, and accepted a teaching and coaching position. More importantly, he met his wife, Gwen Whipple, who was teaching at the same school.",
        ],
    },
    "MS": {
        "gov_name": "Tate Reeves",
        "terms": "2020",
        "birthdate": "June 5, 1974",
        "bith_state": "Mississippi",
        "school": "Millsaps College",
        "bio": [
            "As the 65th Governor of Mississippi, Tate Reeves continues to build on his strong record as a conservative leader who fights to guard taxpayers’ dollars, improve educational opportunity, and grow new careers so that our state’s best and brightest can raise their families and thrive here at home. In his inaugural address, Governor Reeves promised that this would be an administration for all Mississippi. He committed to a mission to create a climate where good careers are plentiful with every Mississippian prepared to pursue them, as he has every single day of his time serving our state. Upon taking office, Governor Reeves inherited a crumbling corrections department and a scandal-plagued human services department. He took immediate action to stem the existing issues and begin the process of rebuilding, shedding light on the issues and installing the best leadership to help him turn the departments around to work for the people of Mississippi."
        ],
    },
    "MO": {
        "gov_name": "Mike Parson",
        "terms": "2018",
        "birthdate": "September 17, 1955",
        "bith_state": "Missouri",
        "school": "University of Maryland, University of Hawaii",
        "bio": [
            "Michael L. Parson was sworn in as Missouri’s 57th Governor on June 1, 2018. Governor Parson came into the role of Governor with a lifelong commitment to serving others and over 30 years of experience in public service. He previously served as the 47th Lieutenant Governor of Missouri from 2017–2018.",
            "Governor Parson also served six years in the U.S. Army and as the Sheriff of Polk County from 1993–2005. He served in the Missouri House of Representatives from 2005–2011 and in the Missouri Senate from 2011–2017. As a member of Missouri’s General Assembly, Governor Parson sponsored and co-sponsored several landmark pieces of legislation including Missouri’s Castle Doctrine, which strengthened 2nd Amendment rights, and the Missouri Farming Rights Amendment, a piece of legislation that changed the Missouri Constitution to guarantee all Missourians the right to farm and ranch.",
            "From day one, workforce development and infrastructure have been the top priorities for Governor Parson. Working with the General Assembly, Governor Parson established the Focus on Bridges program, which will repair or replace 250 bridges throughout the state.",
        ],
    },
    "MT": {
        "gov_name": "Greg Gianforte",
        "terms": "2021",
        "birthdate": "April 17, 1961",
        "bith_state": "California",
        "school": "Unlisted",
        "bio": [
            "Montanans elected Greg Gianforte as their state’s 25th governor on November 3, 2020. Gianforte received more votes than any candidate for governor in Montana history and won with the largest margin for a first-term governor since 1920. Gianforte spent his entire career focusing on creating jobs and opportunities. He founded five different startup companies. He’s worked to improve Montana’s economy through the “Better Montana Jobs” project. He also launched scholarship programs to help low-income students and veterans pursue the education and training they need to start a career in Montana.\xa0Married since 1986, Greg and Susan Gianforte raised their four children in Bozeman hunting, fishing, rafting, climbing, skiing and backpacking on Montana’s public lands."
        ],
    },
    "NE": {
        "gov_name": "Jim Pillen",
        "terms": "2023",
        "birthdate": "December 31, 1955",
        "bith_state": "Nebraska",
        "school": "University of Nebraska, Lincoln | Kansas State University",
        "bio": [
            "Governor Jim Pillen was sworn in as Nebraska’s 41st Governor on January 5, 2023.",
            "Governor Pillen grew up on a farm in Platte County, Nebraska and raised pigs with his father, Dale. He graduated from Lakeview High School.\xa0He earned a Bachelor’s Degree in Animal Science from UNL, and married Suzanne Shreve. Governor Pillen then earned a doctor of veterinary medicine from Kansas State. In 1983, he returned to Nebraska and opened a small animal practice and swine consulting practice.",
            "Governor Pillen and his father, Dale, partnered together, raising 60 sows and 1,200 market hogs on a dirt lot on their home farm. In 1993, Jim started Pillen Family Farms. In 2003, he added DNA Genetics.\u202fIn 2010, his two oldest children, Sarah and Brock, joined the business. Pillen Family Farms and DNA Genetics are now a multigenerational family-run business, composed of over 1,100 team members.\u202fThe family business operates by some basic core beliefs—do what is right, do the best you can, and treat others the way you want to be treated.",
        ],
    },
    "NV": {
        "gov_name": "Joe Lombardo",
        "terms": "2023",
        "birthdate": "November 8, 1962",
        "bith_state": "Other",
        "school": "University of Nevada, Las Vegas",
        "bio": [
            "Joe Lombardo began his service to others in the United States Army, serving in the Army, National Guard, and Army. After his service to his country, Joe dedicated himself to protecting our communities – serving in law enforcement over the last 30 years. Governor Lombardo quickly rose through the ranks of the Las Vegas Metropolitan Police Department (LVMPD) and, after 26 years on the force, was elected as Sheriff of Clark County, Nevada, in 2014. ",
            "Sheriff Lombardo’s professional affiliations include Major Cities Chiefs Association (MCCA), Major County Sheriffs of America (MCSA), National Sheriffs Association (NSA), FBI – Law Enforcement Executive Development Association (LEEDA), Vice-Chair Nevada Commission for Homeland Security and Federal Bureau of Investigation (FBI) National Academy Associates. He has also served as Board Member for the LVMPD Foundation (2007-2014), After School All-Stars (2015-2020), Goodwill of Southern Nevada (2007-2009), Make A Wish (2015-2020), Committee Member for the NV Communications Steering Committee (2012-2014) and MCC’s representative to the Public Safety Advisory Committee (2012-2014). ",
            "Governor Lombardo holds a B.S. and a M.S. in crisis management, both from UNLV.",
        ],
    },
    "NH": {
        "gov_name": "Chris Sununu",
        "terms": "2017",
        "birthdate": "November 5, 1974",
        "birth_state": "New Hampshire",
        "school": "Massachusetts Institute of Technology",
        "bio": [
            "Governor Christopher T. Sununu is the 82nd Governor of the State of New Hampshire. Before being elected Governor in 2016, Gov. Sununu served three terms on the New Hampshire Executive Council representing 32 cities and towns in Rockingham and Hillsborough counties. In 2010, Gov. Sununu led a group of investors in the buyout of Waterville Valley Resort where he worked as Chief Executive Officer and was in charge of an expansion of the ski resort done in cooperation with the United States Forest Service. An environmental engineer, Gov. Sununu worked for ten years cleaning up hazardous waste sites across the country.",
            "Gov. Sununu grew up in Salem, NH. He graduated from Massachusetts Institute of Technology (M.I.T.) with a BS in Civil/Environmental Engineering. Gov. Sununu lives in Newfields with his wife, Valerie, and their three children, Calvin, Edie, and Leo.",
        ],
    },
    "NJ": {
        "gov_name": "Phil Murphy",
        "terms": "2018",
        "birthdate": "August 16, 1957",
        "birth_state": "Massachusetts",
        "school": "University of Pennsylvania, Wharton School of the University of Pennsylvania, Harvard University",
        "bio": [
            "Governor Phil Murphy, as he says, “grew up in a family that was middle class on a good day,” the youngest of four children with only one parent who graduated high school. His upbringing – where religion, a strong work ethic, education, and civic awareness were pillars of family life – shaped his values, his priorities, and the leader he is.",
            "Prior to taking office, Governor Murphy had long been deeply engaged in civic life and philanthropic pursuits. He has led and supported charities to lift up troubled teens and domestic abuse survivors. Nationally, he served proudly as New Jersey’s sole representative on the board of the NAACP, the world’s oldest civil rights organization, and as Finance Chair of the Democratic National Committee. The Governor has also led national and state task forces, respectively, on education and public employee pensions and benefits. In 2009, he answered President Obama’s call to service and, following his confirmation by the United States Senate, became the U.S. Ambassador to the Federal Republic of Germany,\xa0where he served until 2013.",
            "Governor Murphy and First Lady Tammy Murphy live in Monmouth County and are the parents of Josh, Emma, Charlie, and Sam. A proud public-school product, Governor Murphy holds degrees from Harvard University and the Wharton School of Business at the University of Pennsylvania.",
        ],
    },
    "NM": {
        "gov_name": "Michelle Lujan Grisham",
        "terms": "2019",
        "birthdate": "October 24, 1959",
        "birth_state": "New Mexico",
        "school": "University of New Mexico",
        "bio": [
            "Michelle Lujan Grisham is the thirty-second governor of the state of New Mexico, the first Democratic Latina to be elected governor in U.S. history. A longtime state Cabinet secretary at both the New Mexico Department of Aging and Long-term Services and Department of Health, Gov. Lujan Grisham has been a leading advocate for senior citizens, veterans and the disabled as well as investments in health care infrastructure and innovative programming that has improved access and quality of care for New Mexicans across the state. She was elected to the U.S. Congress in 2011, serving three terms in Washington on behalf of New Mexico’s 1st Congressional District.",
            "Gov. Lujan Grisham was born in Los Alamos and graduated from St. Michael’s High School in Santa Fe before earning undergraduate and law degrees from the University of New Mexico. A 12th-generation New Mexican, she is the mother of two adult children and grandmother of three",
        ],
    },
    "NY": {
        "gov_name": "Kathy Hochul",
        "terms": "2021",
        "birthdate": "August 27, 1958",
        "birth_state": "New York",
        "school": "Unlisted",
        "bio": [
            "Kathy Hochul is the 57th and first female Governor of New York State. Governor Kathy Hochul began her career in public service on her local Town Board before serving as Erie County Clerk, and then as a member of Congress for New York’s 26th Congressional District. She more recently served in statewide office as Lieutenant Governor and now as the first female Governor of the State of New York.",
            "As Lieutenant Governor from 2015 to 2021, Hochul successfully spearheaded numerous initiatives and\u202flead the\u202fadministration’s economic development\u202fand job creation\u202fefforts across the state, working every day to advocate\u202ffor policies that help all\u202fNew Yorkers\u202fmake ends meet. She also helped New York State manage the COVID-19 pandemic response, while focusing on a recovery that builds back better and more inclusive.",
        ],
    },
    "NC": {
        "gov_name": "Roy Cooper",
        "terms": "2017",
        "birthdate": "June 13, 1957",
        "birth_state": "North Carolina",
        "school": "University of North Carolina at Chapel Hill",
        "bio": [
            "Governor Roy Cooper has spent nearly three decades in public service protecting families, keeping communities safe, and working to create jobs and improve schools. The son of a school teacher, he knows that education creates opportunity and he has worked throughout his career to strengthen our schools and create a sound foundation for our state’s children.",
            "In the NC House and Senate, Gov. Cooper fought to increase teacher pay and reduce class sizes. He wrote North Carolina’s first children’s health insurance initiative. During his service in the legislature, Gov. Cooper worked with members of both parties to get balanced budgets that raised teacher pay to the national average, grow the economy and cut taxes for middle class families. In 2000, the people of North Carolina elected Gov. Cooper as Attorney General, where he continued to fight for families during his four terms.",
            "Born and raised in Nash County, he attended public schools and worked summers on the family farm before attending UNC-Chapel Hill on a Morehead Scholarship. His mother, Beverly Cooper, worked as a school teacher, and his father, Roy Cooper Jr., farmed and practiced law. After earning a law degree from UNC, Roy Cooper returned home to Nash County to practice law and, with his wife Kristin, raise three daughters – Hilary, Natalie, and Claire.",
        ],
    },
    "ND": {
        "gov_name": "Doug Burgum",
        "terms": "2016",
        "birthdate": "August 1, 1956",
        "birth_state": "North Dakota",
        "school": "North Dakota State University, Stanford University",
        "bio": [
            "Governor Doug Burgum took office as the 33rd governor of North Dakota on December 15, 2016. Prior to being elected Governor, Gov. Burgum led Great Plains as CEO through its initial public offering in 1997 and acquisition by Microsoft Corp. in 2001. In 2006, Gov. Burgum reaffirmed his passion for North Dakota by founding Kilbourne Group, a real estate development firm committed to creating smart, healthy cities through vibrant downtowns. In 2008, he co-founded Arthur Ventures, a venture capital firm that invests in ambitious, mission-driven software companies. In 2009, then-Gov. John Hoeven awarded Gov. Burgum the Theodore Roosevelt Rough Rider Award, North Dakota’s highest citizen honor. The award recognized Burgum for his business leadership and numerous philanthropic efforts, including the Doug Burgum Family Fund, which focuses its charitable giving on youth and education.",
            "Born August 1, 1956, Gov. Burgum grew up in Arthur, N.D. He has maintained his commitment and connection to his roots through family farm partnerships, by serving as a member for Arthur Companies, Inc., a diversified agribusiness company founded by his grandparents in 1906, and through a ranching partnership in the Badlands of western North Dakota. Gov. Burgum graduated with a bachelor’s degree in university studies from North Dakota State University in 1978. He earned a master’s of business administration from the Stanford University Graduate School of Business in 1980.",
            "Gov. Burgum is married to Kathryn Burgum and has two sons, Joe and Tom, and a daughter, Jesse.",
        ],
    },
    "OH": {
        "gov_name": "Mike DeWine",
        "terms": "2019",
        "birthdate": "January 5, 1947",
        "bith_state": "Ohio",
        "school": "Miami University, Ohio Northern University",
        "bio": [
            "On November 6, 2018, Mike DeWine was elected to serve as the 70th Governor of the State of Ohio. Gov. DeWine has had a long and distinguished career in public service, focusing on protecting Ohio children and families. He was previously the 50th\xa0Attorney General of Ohio and has previously been elected to serve as Greene County Prosecutor, Ohio State Senator, U.S. Congressman, Ohio Lt. Governor, U.S. Senator.",
            "Raised in Yellow Springs, Ohio, Mike DeWine and Fran (Struewing) met in the first grade and married while students at Miami University. They’ve been blessed with eight children and 26\xa0grandchildren.",
        ],
    },
    "OK": {
        "gov_name": "Kevin Stitt",
        "terms": "2019",
        "birthdate": "December 28, 1972",
        "bith_state": "Florida",
        "school": "Oklahoma State University",
        "bio": [
            "J. Kevin Stitt is the 28th governor of Oklahoma. Gov. Stitt is an entrepreneur and businessman who founded Gateway in Tulsa, Oklahoma, in 2000. Starting Gateway with only $1,000 and a computer, he grew his business into one of the top 20 mortgage lenders and servicers in the nation, operating in more than 40 states and servicing more than $20 billion in residential mortgages. Stitt led Gateway through a merger with Farmers Exchange Bank in 2018 and formed Gateway First Bank, which is headquartered in Jenks, Oklahoma, and operates more than 160 mortgage centers across the country and employs more than 1,400 people.",
            "He is a fourth-generation Oklahoman who graduated from Norman High School and is an alumnus of Oklahoma State University, where he received an accounting degree in 1996. Stitt and his wife, Sarah, have six children and have been married for 22 years.",
        ],
    },
    "OR": {
        "gov_name": "Tina Kotek",
        "terms": "2023",
        "birthdate": "September 30, 1966",
        "bith_state": "Pennsylvania",
        "school": "University of Oregon, University of Washington",
        "bio": [
            "Governor Tina Kotek is the daughter of proud first-generation Americans who believed in hard work, being informed citizens, and encouraging their children to follow their dreams.",
            "Moving to Oregon from the East Coast in 1987, Kotek fell in love with the beauty of the state and the openness of the people. She earned an undergraduate degree at the University of Oregon and a graduate degree at the University of Washington – where she advocated for and won domestic partnership rights for faculty and students.",
            "Returning to Oregon after graduation, Kotek took a job at the Oregon Food Bank, attracted to their mission to end hunger, not just feed people. During this time, Kotek advocated for ways to reduce food insecurity – like a strong minimum wage, housing assistance, and access to health insurance. Kotek continued her advocacy for children as policy director for Children First for Oregon.",
        ],
    },
    "PA": {
        "gov_name": "Josh Shapiro",
        "terms": "2023",
        "birthdate": "June 20, 1973",
        "bith_state": "Missouri",
        "school": "University of Rochester, Georgetown University Law Center",
        "bio": [
            "Governor Josh Shapiro grew up in Pennsylvania, watching his parents serve their community — his father was a pediatrician, and his mother was an educator. Their example inspired Josh to enter public service.",
            "After graduating from the University of Rochester, Shapiro began working in government while putting himself through law school at night before returning to his hometown and winning election as State Representative. As a Representative from 2005 – 2021, Shapiro helped write and pass some of the toughest ethics laws in state history.",
            "Next, Governor Shapiro was elected Chairman of the Board of Commissioners in Montgomery County, Pennsylvania’s third-largest. Confronting $10 million budget deficit and an underfunded pension for county employees, Shapiro put the county back on solid financial footing, took early steps to combat the heroin epidemic, and helped the first LGBTQ+ couples in Pennsylvania marry.",
        ],
    },
    "RI": {
        "gov_name": "Dan McKee",
        "terms": "2021",
        "birthdate": "June 16, 1951",
        "birth_state": "Rhode Island",
        "school": "Assumption College, Harvard University",
        "bio": [
            "Daniel J. McKee was sworn in as the 76th Governor of Rhode Island on March 2, 2021. As lieutenant governor from 2015 to 2021, Dan focused on creating more economic opportunity for all Rhode Island families and building solvent communities.",
            "As a small businessman and elected official, he has spent his adult life advocating for positive change in Rhode Island. His record is one of strong fiscal management, visionary education initiatives and thoughtful economic development.",
            "His tenure at the State House had been marked by the same leadership approach. He used the lieutenant governor’s office to support small businesses, improve the state’s economic situation and be a champion of Rhode Island’s cities and towns, which have been underrepresented.",
        ],
    },
    "SC": {
        "gov_name": "Henry McMaster",
        "terms": "2017",
        "birthdate": "May 27, 1947",
        "birth_state": "South Carolina",
        "school": "University of South Carolina",
        "bio": [
            "Governor Henry Dargan McMaster, a longtime public servant of South Carolina, was born May 27, 1947, in Columbia, South Carolina. He received a bachelor’s degree in history from the University of South Carolina in 1969 and as an undergraduate was a member of Kappa Alpha Order and the South Carolina Student Legislature.",
            "In 1973, he graduated from the University of South Carolina School of Law, where he was on the editorial board of the South Carolina Law Review. Later that year, he was admitted to the Richland County Bar Association. He also served in the U.S. Army Reserves, receiving an honorable discharge in 1975.",
            "Upon graduation from law school, he was a legislative assistant to U.S. Senator Strom Thurmond in Washington, D.C., and joined the law firm of Tompkins and McMaster in 1974. He was later admitted to practice before the U.S. District Court, U.S. Court of Claims, the U.S. Court of Appeals for the Fourth Circuit, and the Supreme Court of the United States. Governor McMaster practiced law for over 40 years, as a federal and state prosecutor and in private practice in both state and federal courts.",
        ],
    },
    "SD": {
        "gov_name": "Kristi Noem",
        "terms": "2019",
        "birthdate": "November 30, 1971",
        "birth_state": "South Dakota",
        "school": "South Dakota State University",
        "bio": [
            "Governor Kristi Noem is a wife, a mother, and a lifelong rancher, farmer and small business owner.",
            "In 2010, after serving in the South Dakota legislature for several years, Gov. Noem was elected to serve as South Dakota’s lone member of the U.S. House of Representatives. In 2018, with the platform of protecting South Dakotans against tax increases, government growth, federal intrusion, and government secrecy, she was elected as South Dakota’s first-ever female Governor.",
            "Gov. Noem often says that her greatest accomplishment is raising her three children, Kassidy, Kennedy, and Booker, with her husband Bryon.",
        ],
    },
    "TN": {
        "gov_name": "Bill Lee",
        "terms": "2019",
        "birthdate": "October 9, 1959",
        "bith_state": "Tennessee",
        "school": "Auburn University",
        "bio": [
            "Bill Lee is a seventh-generation Tennessean and the 50th Governor of Tennessee. He was raised in Franklin, where he still resides today with his wife, Maria, on his family’s farm. He’s the proud father of four adult children (Jessica, twin sons Jacob and Caleb, and Sarah Kate) and eight grandchildren.",
            "After attending Williamson County Schools, Governor Lee attended Auburn University, where he studied Mechanical Engineering. After graduation, he returned home to Franklin to join the family business his grandfather started in 1944, a comprehensive mechanical construction service company. He became president of Lee Company in 1992.",
        ],
    },
    "TX": {
        "gov_name": "Greg Abbott",
        "terms": "2015",
        "birthdate": "November 13, 1957",
        "bith_state": "Texas",
        "school": "University of Texas at Austin, Vanderbilt University Law School",
        "bio": [
            "Greg Abbott is the 48th Governor of the State of Texas. Before his election in 2014, Greg Abbott was the 50th and longest-serving Attorney General of Texas, where he earned a national reputation for defending religious liberty and protecting Texas communities and children. He also previously served as a Justice on the Texas Supreme Court and as a State District Judge in Harris County.",
            "Governor Abbott was born in Wichita Falls and raised in Duncanville. After graduating from The University of Texas at Austin, he earned a law degree from Vanderbilt University Law School.",
            "Governor Abbott and his wife, Cecilia, a former teacher and principal, and the first Hispanic First Lady of Texas, were married in 1981. Their daughter, Audrey, is a recent college graduate.",
        ],
    },
    "UT": {
        "gov_name": "Spencer Cox",
        "terms": "2021",
        "birthdate": "July 11, 1975",
        "bith_state": "Utah",
        "school": "Snow College, Utah State University, Washington and Lee University School of Law",
        "bio": [
            "Gov. Spencer J. Cox is a husband, father, farmer, recovering attorney, and Utah’s 18th governor.",
            "Gov. Cox has a long track record of public service, serving as a city councilmember, mayor, county commissioner and state legislator before being appointed as Utah’s lieutenant governor in 2013. He was sworn in as governor on Jan. 4, 2021.",
            "During his first term in office, Gov. Cox has cut $1.1 billion in taxes, implemented landmark changes in water law, water conservation and infrastructure planning, locked in record funding for education and teachers, enacted universal school choice, and secured funds for affordable housing. A long-time advocate for suicide prevention and mental health resources, he’s become a national voice on protecting youth from the harms of social media. He also signed early education and workforce program funding, launched the One Utah Health Collaborative, and expanded opportunity for women, diverse communities and those living in rural parts of the state.",
        ],
    },
    "VT": {
        "gov_name": "Phil Scott",
        "terms": "2017",
        "birthdate": "August 4, 1958",
        "bith_state": "Vermont",
        "school": "University of Vermont",
        "bio": [
            "Phil Scott became the 82nd Governor of Vermont in January 2017. Previously, he was elected and served three terms (2011-2017) as Vermont’s 79th Lieutenant Governor. Prior to that role, he was elected to the Vermont Senate for five terms, representing Washington County. During his 10-year service in the Senate, he was Vice Chair of the Transportation Committee and Chair of the Institutions Committee.",
            "He is a lifelong Vermonter who grew up in Barre and graduated from Spaulding High School and the University of Vermont. He lives in Berlin with his wife Diana McTeague Scott, and has two grown daughters, Erica and Rachael.",
        ],
    },
    "VA": {
        "gov_name": "Glenn Youngkin",
        "terms": "2022",
        "birthdate": "December 9, 1966",
        "bith_state": "Virginia",
        "school": "Unlisted",
        "bio": [
            "Glenn Youngkin is a homegrown Virginian who grew up in Richmond and Virginia Beach. As his father changed jobs, Governor Youngkin learned that moving around didn’t equal moving up – nothing was handed to him. From his first job washing dishes and frying eggs at a diner in Virginia Beach, he embraced hard work and responsibility to help his family when his father lost his job. His determination to succeed earned him multiple high school basketball honors in Virginia and an athletic scholarship to college.",
            "After earning an engineering degree at Rice University, and his MBA at Harvard Business School, Governor Youngkin and his wife Suzanne moved to Northern Virginia. He landed a job at The Carlyle Group, where he spent the next 25 years. Working his way to the top of the company, Governor Youngkin played a key role in building Carlyle into one of the leading investment firms in the world. His efforts have helped fund the retirements of teachers, police officers, firefighters and other frontline public servants and supported hundreds of thousands of American jobs.",
            "Married for over 27 years to his amazing wife Suzanne, Governor Youngkin is a dedicated father of four wonderful children. Their family journey has been and continues to be guided by their faith.",
        ],
    },
    "WA": {
        "gov_name": "Jay Inslee",
        "terms": "2013",
        "birthdate": "February 9, 1951",
        "bith_state": "Washington",
        "school": "University of Washington; Willamette University",
        "bio": [
            "Jay Inslee is a fifth-generation Washingtonian who has lived and worked in urban and rural communities on both sides of the state. Governor Inslee worked his way through college and graduated from the University of Washington with a degree in economics before earning his law degree at Willamette University. He and his wife, Trudi, then moved to Selah, a small town near Yakima where they raised their three sons. Jay worked as an attorney and prosecutor.",
            "Governor Inslee first became involved in public service in 1985 when he and Trudi helped lead the effort to build a new public high school in Selah. Motivated to fight against proposed funding cuts for rural schools, he went on to represent the 14th Legislative District in the state House of Representatives. Governor Inslee continued serving communities in the Yakima Valley when he was elected to Congress in 1992. The Inslees later moved back to the Puget Sound area where Governor Inslee was elected to Congress in 1998, serving until 2012 when he was elected governor. He was re-elected in 2016.",
        ],
    },
    "WV": {
        "gov_name": "Jim Justice",
        "terms": "2017",
        "birthdate": "April 27, 1951",
        "birth_state": "West Virginia",
        "school": "Unlisted",
        "bio": [
            "James C. Justice, II was born April 27, 1951, to James Conley Justice and Edna Ruth Justice. He attended Raleigh County public schools and graduated from Woodrow Wilson High School in 1969, attended Greenbrier Military Academy as a post graduate. Governor Justice went to Marshall University in Huntington, West Virginia, and was captain of the golf team for two years before earning his undergraduate degree and a Masters in Business Administration.",
            "In May 2015, Jim announced his campaign to seek the office of governor of West Virginia. After 19 months on the campaign trail sharing his vision for transforming West Virginia, Jim was elected the 36th governor of West Virginia. The Governor and the First Lady have two children, James (Jay) C. Justice, III and Dr. Jill Justice.",
        ],
    },
    "WI": {
        "gov_name": "Tony Evers",
        "terms": "2019",
        "birthdate": "November 5, 1951",
        "bith_state": "Wisconsin",
        "school": "University of Wisconsin-Madison",
        "bio": [
            "On November 6, 2018, the people of Wisconsin voted Tony Evers the 46th governor of Wisconsin. Prior to his election, he served as the Wisconsin State Superintendent of Public Instruction winning statewide elections in 2009, 2013, and 2017. With over three decades of public education experience, Governor Evers has dedicated his life to fighting for Wisconsin’s kids and serving the people of Wisconsin.",
            "Born and raised in Plymouth, Wisconsin, Governor\xa0Evers graduated from Plymouth High School and earned his bachelor’s, master’s, and doctoral degree in educational administration from the University of Wisconsin-Madison. He is married to his high school sweetheart, Kathy, an educator. They are parents of three adult children, all public school graduates, and have nine grandchildren.",
        ],
    },
    "WY": {
        "gov_name": "Mark Gordon",
        "terms": "2019",
        "birthdate": "March 14, 1957",
        "bith_state": "New York",
        "school": "Middlebury College",
        "bio": [
            "Mark Gordon grew up on the family ranch in Wyoming where he learned the values of hard work and integrity and the importance of working together. As Governor, he brings those values to the table, maintaining his commitment to a Wyoming where its citizens can pursue their dreams while the state retains its unique character. He is a strong believer that Wyoming must chart its own course, and a steadfast defender of its interests to do so.",
            "Governor Gordon has worked tirelessly to set Wyoming on a sustainable fiscal path. He is committed to making government more transparent, accessible, productive and efficient. He believes government is best when it is closest to the people, and is committed to giving local communities the tools they need to thrive. He is a staunch advocate of quality education for all children from bottom to top, K-12 through all forms of post-secondary education, private and public.",
            "Governor Gordon served as Wyoming State Treasurer from October 2012 until January 2019 when he was sworn in as Governor. He was ranked 57 th among the Sovereign Wealth Fund institute’s “most significant and impactful public investor executives” in 2013. During his time in office, he transformed and modernized the management of the state’s financial portfolio. In 2016 , Wyoming earned the No. 1 ranking in the United States and No. 3 in the world for “transparency and accountability” among all sovereign funds by the Peterson Institute.",
        ],
    },
}
