
New-Hampshire
"terms": January 5, 2017 - January 1, 2019January 2, 2019 - January 6, 2021January 7, 2021 - January 5, 2023January 5, 2023 - Current
"birthdate": November 5, 1974
"birth_state": New Hampshire
"school": Massachusetts Institute of Technology
"bio": ['Governor Christopher T. Sununu is the 82nd Governor of the State of New Hampshire. Before being elected Governor in 2016, Gov. Sununu served three terms on the New Hampshire Executive Council representing 32 cities and towns in Rockingham and Hillsborough counties. In 2010, Gov. Sununu led a group of investors in the buyout of Waterville Valley Resort where he worked as Chief Executive Officer and was in charge of an expansion of the ski resort done in cooperation with the United States Forest Service. An environmental engineer, Gov. Sununu worked for ten years cleaning up hazardous waste sites across the country.', 'Gov. Sununu grew up in Salem, NH. He graduated from Massachusetts Institute of Technology (M.I.T.) with a BS in Civil/Environmental Engineering. Gov. Sununu lives in Newfields with his wife, Valerie, and their three children, Calvin, Edie, and Leo.', "This searchable database identifies former governors by state and dates of service. The governors' biographies available on the NGA website provide summary biographical information only and are edited infrequently."]
New-Jersey:
"terms": 'January 16, 2018 - January 18, 2022January 18, 2022 - Current',
"birthdate": 'August 16, 1957',
"birth_state": 'Massachusetts',
"school": 'University of Pennsylvania, Wharton School of the University of Pennsylvania, Harvard University',
"bio": ['Governor Phil Murphy, as he says, “grew up in a family that was middle class on a good day,” the youngest of four children with only one parent who graduated high school. His upbringing – where religion, a strong work ethic, education, and civic awareness were pillars of family life – shaped his values, his priorities, and the leader he is.', 'Prior to taking office, Governor Murphy had long been deeply engaged in civic life and philanthropic pursuits. He has led and supported charities to lift up troubled teens and domestic abuse survivors. Nationally, he served proudly as New Jersey’s sole representative on the board of the NAACP, the world’s oldest civil rights organization, and as Finance Chair of the Democratic National Committee. The Governor has also led national and state task forces, respectively, on education and public employee pensions and benefits. In 2009, he answered President Obama’s call to service and, following his confirmation by the United States Senate, became the U.S. Ambassador to the Federal Republic of Germany,\xa0where he served until 2013.', 'Governor Murphy and First Lady Tammy Murphy live in Monmouth County and are the parents of Josh, Emma, Charlie, and Sam. A proud public-school product, Governor Murphy holds degrees from Harvard University and the Wharton School of Business at the University of Pennsylvania.']
New-York
"terms": 'August 24, 2021 - January 1, 2023January 1, 2023 - Current',
"birthdate": 'August 27, 1958',
"birth_state": 'New York',
"school": 'Unlisted',
"bio": ['Kathy Hochul is the 57th and first female Governor of New York State. Governor Kathy Hochul began her career in public service on her local Town Board before serving as Erie County Clerk, and then as a member of Congress for New York’s 26th Congressional District. She more recently served in statewide office as Lieutenant Governor and now as the first female Governor of the State of New York.', 'As Lieutenant Governor from 2015 to 2021, Hochul successfully spearheaded numerous initiatives and\u202flead the\u202fadministration’s economic development\u202fand job creation\u202fefforts across the state, working every day to advocate\u202ffor policies that help all\u202fNew Yorkers\u202fmake ends meet. She also helped New York State manage the COVID-19 pandemic response, while focusing on a recovery that builds back better and more inclusive.', 'Read More…']
New-Mexico
"terms": 'January 1, 2019 - January 1, 2023January 1, 2023 - Current',
"birthdate": 'October 24, 1959',
"birth_state": 'New Mexico',
"school": 'University of New Mexico',
"bio": ['Michelle Lujan Grisham is the thirty-second governor of the state of New Mexico, the first Democratic Latina to be elected governor in U.S. history. A longtime state Cabinet secretary at both the New Mexico Department of Aging and Long-term Services and Department of Health, Gov. Lujan Grisham has been a leading advocate for senior citizens, veterans and the disabled as well as investments in health care infrastructure and innovative programming that has improved access and quality of care for New Mexicans across the state. She was elected to the U.S. Congress in 2011, serving three terms in Washington on behalf of New Mexico’s 1st Congressional District.', 'Gov. Lujan Grisham was born in Los Alamos and graduated from St. Michael’s High School in Santa Fe before earning undergraduate and law degrees from the University of New Mexico. A 12th-generation New Mexican, she is the mother of two adult children and grandmother of three', "This searchable database identifies former governors by state and dates of service. The governors' biographies available on the NGA website provide summary biographical information only and are edited infrequently."]
North-Carolina
"terms": 'January 1, 2017 - December 31, 2020January 1, 2021 - Current',
"birthdate": 'June 13, 1957',
"birth_state": 'North Carolina',
"school": 'University of North Carolina at Chapel Hill',
"bio": ['Governor Roy Cooper has spent nearly three decades in public service protecting families, keeping communities safe, and working to create jobs and improve schools. The son of a school teacher, he knows that education creates opportunity and he has worked throughout his career to strengthen our schools and create a sound foundation for our state’s children.', 'In the NC House and Senate, Gov. Cooper fought to increase teacher pay and reduce class sizes. He wrote North Carolina’s first children’s health insurance initiative. During his service in the legislature, Gov. Cooper worked with members of both parties to get balanced budgets that raised teacher pay to the national average, grow the economy and cut taxes for middle class families. In 2000, the people of North Carolina elected Gov. Cooper as Attorney General, where he continued to fight for families during his four terms.', 'Born and raised in Nash County, he attended public schools and worked summers on the family farm before attending UNC-Chapel Hill on a Morehead Scholarship. His mother, Beverly Cooper, worked as a school teacher, and his father, Roy Cooper Jr., farmed and practiced law. After earning a law degree from UNC, Roy Cooper returned home to Nash County to practice law and, with his wife Kristin, raise three daughters – Hilary, Natalie, and Claire.']
North-Dakota
"terms": 'December 15, 2016 - December 14, 2020December 15, 2020 - Current',
"birthdate": 'August 1, 1956',
"birth_state": 'North Dakota',
"school": 'North Dakota State University, Stanford University',
"bio": ['Governor Doug Burgum took office as the 33rd governor of North Dakota on December 15, 2016. Prior to being elected Governor, Gov. Burgum led Great Plains as CEO through its initial public offering in 1997 and acquisition by Microsoft Corp. in 2001. In 2006, Gov. Burgum reaffirmed his passion for North Dakota by founding Kilbourne Group, a real estate development firm committed to creating smart, healthy cities through vibrant downtowns. In 2008, he co-founded Arthur Ventures, a venture capital firm that invests in ambitious, mission-driven software companies. In 2009, then-Gov. John Hoeven awarded Gov. Burgum the Theodore Roosevelt Rough Rider Award, North Dakota’s highest citizen honor. The award recognized Burgum for his business leadership and numerous philanthropic efforts, including the Doug Burgum Family Fund, which focuses its charitable giving on youth and education.', 'Born August 1, 1956, Gov. Burgum grew up in Arthur, N.D. He has maintained his commitment and connection to his roots through family farm partnerships, by serving as a member for Arthur Companies, Inc., a diversified agribusiness company founded by his grandparents in 1906, and through a ranching partnership in the Badlands of western North Dakota. Gov. Burgum graduated with a bachelor’s degree in university studies from North Dakota State University in 1978. He earned a master’s of business administration from the Stanford University Graduate School of Business in 1980.', 'Gov. Burgum is married to Kathryn Burgum and has two sons, Joe and Tom, and a daughter, Jesse.']
Rhode-Island
"terms": 'March 2, 2021 - January 3, 2023January 3, 2023 - Current',
"birthdate": 'June 16, 1951',
"birth_state": 'Rhode Island',
"school": 'Assumption College, Harvard University',
"bio": ['Daniel J. McKee was sworn in as the 76th Governor of Rhode Island on March 2, 2021. As lieutenant governor from 2015 to 2021, Dan focused on creating more economic opportunity for all Rhode Island families and building solvent communities.', 'As a small businessman and elected official, he has spent his adult life advocating for positive change in Rhode Island. His record is one of strong fiscal management, visionary education initiatives and thoughtful economic development.', 'His tenure at the State House had been marked by the same leadership approach. He used the lieutenant governor’s office to support small businesses, improve the state’s economic situation and be a champion of Rhode Island’s cities and towns, which have been underrepresented.']
South-Carolina
"terms": 'January 24, 2017 - January 8, 2019January 8, 2019 - January 11, 2023January 11, 2023 - Current',
"birthdate": 'May 27, 1947',
"birth_state": 'South Carolina',
"school": 'University of South Carolina',
"bio": ['Governor Henry Dargan McMaster, a longtime public servant of South Carolina, was born May 27, 1947, in Columbia, South Carolina. He received a bachelor’s degree in history from the University of South Carolina in 1969 and as an undergraduate was a member of Kappa Alpha Order and the South Carolina Student Legislature.', 'In 1973, he graduated from the University of South Carolina School of Law, where he was on the editorial board of the South Carolina Law Review. Later that year, he was admitted to the Richland County Bar Association. He also served in the U.S. Army Reserves, receiving an honorable discharge in 1975.', 'Upon graduation from law school, he was a legislative assistant to U.S. Senator Strom Thurmond in Washington, D.C., and joined the law firm of Tompkins and McMaster in 1974. He was later admitted to practice before the U.S. District Court, U.S. Court of Claims, the U.S. Court of Appeals for the Fourth Circuit, and the Supreme Court of the United States. Governor McMaster practiced law for over 40 years, as a federal and state prosecutor and in private practice in both state and federal courts.']
South-Dakota
"terms": 'January 8, 2019 - January 7, 2023January 7, 2023 - Current',
"birthdate": 'November 30, 1971',
"birth_state": 'South Dakota',
"school": 'South Dakota State University',
"bio": ['Governor Kristi Noem is a wife, a mother, and a lifelong rancher, farmer and small business owner.', 'In 2010, after serving in the South Dakota legislature for several years, Gov. Noem was elected to serve as South Dakota’s lone member of the U.S. House of Representatives. In 2018, with the platform of protecting South Dakotans against tax increases, government growth, federal intrusion, and government secrecy, she was elected as South Dakota’s first-ever female Governor.', 'Gov. Noem often says that her greatest accomplishment is raising her three children, Kassidy, Kennedy, and Booker, with her husband Bryon.']
West-Virginia
"terms": 'January 16, 2017 - January 17, 2021January 18, 2021 - Current',
"birthdate": 'April 27, 1951',
"birth_state": 'West Virginia',
"school": 'Unlisted',
"bio": ['James C. Justice, II was born April 27, 1951, to James Conley Justice and Edna Ruth Justice. He attended Raleigh County public schools and graduated from Woodrow Wilson High School in 1969, attended Greenbrier Military Academy as a post graduate. Governor Justice went to Marshall University in Huntington, West Virginia, and was captain of the golf team for two years before earning his undergraduate degree and a Masters in Business Administration.', 'In May 2015, Jim announced his campaign to seek the office of governor of West Virginia. After 19 months on the campaign trail sharing his vision for transforming West Virginia, Jim was elected the 36th governor of West Virginia. The Governor and the First Lady have two children, James (Jay) C. Justice, III and Dr. Jill Justice.', "This searchable database identifies former governors by state and dates of service. The governors' biographies available on the NGA website provide summary biographical information only and are edited infrequently."]