state_names = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]


state_bird_list = [
    "Yellowhammer",
    "Willow Ptarmigan",
    "Cactus Wren",
    "Northern Mockingbird",
    "California Valley Quail",
    "Lark Bunting",
    "American Robin",
    "Blue Hen Chicken",
    "Mockingbird",
    "Brown Thrasher",
    "Nene",
    "Mountain Bluebird",
    "Cardinal",
    "Cardinal",
    "Eastern Goldfinch",
    "Western Meadowlark",
    "Cardinal",
    "Eastern Brown Pelican",
    "Chickadee",
    "Baltimore Oriole",
    "Chickadee",
    "Robin",
    "Common Loon",
    "Mockingbird",
    "Bluebird",
    "Western Meadowlark",
    "Western Meadowlark",
    "Mountain Bluebird",
    "Purple Finch",
    "Eastern Goldfinch",
    "Roadrunner",
    "Eastern Bluebird",
    "Cardinal",
    "Western Meadowlark",
    "Cardinal",
    "Scissor-tailed Flycatcher",
    "Western Meadowlark",
    "Ruffed Grouse",
    "Rhode Island Red Hen",
    "Carolina Wren",
    "Ring-necked Pheasant",
    "Mockingbird",
    "Mockingbird",
    "Ring-billed Gull",
    "Hermit Thrush",
    "Cardinal",
    "Willow Goldfinch",
    "Cardinal",
    "Robin",
    "Western Meadowlark",
]

state_capitals = [
    "Montgomery",
    "Juneau",
    "Phoenix",
    "Little Rock",
    "Sacramento",
    "Denver",
    "Hartford",
    "Dover",
    "Tallahassee",
    "Atlanta",
    "Honolulu",
    "Boise",
    "Springfield",
    "Indianapolis",
    "Des Moines",
    "Topeka",
    "Frankfort",
    "Baton Rouge",
    "Augusta",
    "Annapolis",
    "Boston",
    "Lansing",
    "Saint Paul",
    "Jackson",
    "Jefferson City",
    "Helena",
    "Lincoln",
    "Carson City",
    "Concord",
    "Trenton",
    "Santa Fe",
    "Albany",
    "Raleigh",
    "Bismarck",
    "Columbus",
    "Oklahoma City",
    "Salem",
    "Harrisburg",
    "Providence",
    "Columbia",
    "Pierre",
    "Nashville",
    "Austin",
    "Salt Lake City",
    "Montpelier",
    "Richmond",
    "Olympia",
    "Charleston",
    "Madison",
    "Cheyenne",
]

state_flowers = [
    "Camellia",
    "Alpine Forget Me Not",
    "Saguaro Cactus Blossom",
    "Apple Blossom",
    "California Poppy",
    "Rocky Mountain Columbine",
    "Mountain Laurel",
    "Peach Blossom",
    "Orange Blossom",
    "Cherokee Rose",
    "Pua Aloalo",
    "Syringa",
    "Violet",
    "Peony",
    "Wild Prairie Rose",
    "Wild Native Sunflower",
    "Goldenrod",
    "Magnolia",
    "White pine cone and tassel",
    "Black-eyed Susan",
    "Trailing-Arbutus (Mayflower)",
    "Apple Blossom",
    "Pink and white lady slipper",
    "Magnolia",
    "White Hawthorn Blossom",
    "Bitterroot",
    "Goldenrod",
    "Sagebrush",
    "Purple lilac",
    "Violet",
    "Yucca flower",
    "Rose",
    "American Dogwood",
    "Wild Prairie Rose",
    "Scarlet Carnation",
    "Oklahoma Rose",
    "Oregon Grape",
    "Mountain Laurel",
    "Common Blue Violet",
    "Yellow Jessamine",
    "Americana Pasque",
    "Iris",
    "Bluebonnet",
    "Sego lily",
    "Red Clover",
    "American Dogwood",
    "Coast Rhododendron",
    "Rhododendron",
    "Wood Violet",
    "Indian Paintbrush",
]

state_govs = [
    "Kay Ivey",
    "Mike Dunleavy",
    "Katie Hobbs",
    "Sarah Huckabee Sanders",
    "Gavin Newsom",
    "Jared Polis",
    "Ned Lamont",
    "John Carney",
    "Ron DeSantis",
    "Brian Kemp",
    "Josh Green",
    "Brad Little",
    "J. B. Pritzker",
    "Eric Holcomb",
    "Kim Reynolds",
    "Laura Kelly",
    "Andy Beshear",
    "John Bel Edwards",
    "Janet Mills",
    "Wes Moore",
    "Maura Healey",
    "Gretchen Whitmer",
    "Tim Walz",
    "Tate Reeves",
    "Mike Parson",
    "Greg Gianforte",
    "Jim Pillen",
    "Joe Lombardo",
    "Chris Sununu",
    "Phil Murphy",
    "Michelle Lujan Grisham",
    "Kathy Hochul",
    "Roy Cooper",
    "Doug Burgum",
    "Mike DeWine",
    "Kevin Stitt",
    "Tina Kotek",
    "Josh Shapiro",
    "Dan McKee",
    "Henry McMaster",
    "Kristi Noem",
    "Bill Lee",
    "Greg Abbott",
    "Spencer Cox",
    "Phil Scott",
    "Glenn Youngkin",
    "Jay Inslee",
    "Jim Justice",
    "Tony Evers",
    "Mark Gordon",
]

state_population = [
    "4,903,185",
    "731,545",
    "7,278,717",
    "3,017,804",
    "39,512,223",
    "5,758,736",
    "3,565,287",
    "973,764",
    "21,477,737",
    "10,617,423",
    "1,415,872",
    "1,787,065",
    "12,671,821",
    "6,732,219",
    "3,155,070",
    "2,913,314",
    "4,467,673",
    "4,648,794",
    "1,344,212",
    "6,045,680",
    "6,892,503",
    "9,986,857",
    "5,639,632",
    "2,976,149",
    "6,137,428",
    "1,068,778",
    "1,934,408",
    "3,080,156",
    "1,359,711",
    "8,882,190",
    "2,096,829",
    "19,453,561",
    "10,488,084",
    "762,062",
    "11,689,100",
    "3,956,971",
    "4,217,737",
    "12,801,989",
    "1,059,361",
    "5,148,714",
    "884,659",
    "6,829,174",
    "28,995,881",
    "3,205,958",
    "623,989",
    "8,535,519",
    "7,614,893",
    "1,792,147",
    "5,822,434",
    "578,759",
]

state_land_area = [
    "50,750",
    "570,641",
    "113,642",
    "52,075",
    "155,973",
    "103,730",
    "4,845",
    "1,955",
    "53,997",
    "57,919",
    "6,423",
    "82,751",
    "55,593",
    "35,870",
    "55,875",
    "81,823",
    "39,732",
    "43,566",
    "30,865",
    "9,775",
    "7,838",
    "56,539",
    "79,617",
    "46,914",
    "68,898",
    "145,556",
    "76,878",
    "109,806",
    "8,969",
    "7,419",
    "121,365",
    "47,224",
    "48,718",
    "68,994",
    "40,953",
    "68,679",
    "96,003",
    "44,820",
    "1,034",
    "30,111",
    "75,898",
    "41,220",
    "261,914",
    "82,168",
    "9,249",
    "39,598",
    "66,582",
    "24,087",
    "54,314",
    "97,105",
]
state_gov_party = [
    "Republican",
    "Republican",
    "Democratic",
    "Republican",
    "Democratic",
    "Democratic",
    "Democratic",
    "Democratic",
    "Republican",
    "Republican",
    "Democratic",
    "Republican",
    "Democratic",
    "Republican",
    "Republican",
    "Democratic",
    "Democratic",
    "Democratic",
    "Democratic",
    "Democratic",
    "Democratic",
    "Democratic",
    "Democratic-Farmer-Labor",
    "Republican",
    "Republican",
    "Republican",
    "Republican",
    "Republican",
    "Republican",
    "Democratic",
    "Democratic",
    "Democratic",
    "Democratic",
    "Republican",
    "Republican",
    "Republican",
    "Democratic",
    "Democratic",
    "Democratic",
    "Republican",
    "Republican",
    "Republican",
    "Republican",
    "Republican",
    "Republican",
    "Republican",
    "Democratic",
    "Republican",
    "Democratic",
    "Republican",
]
